version: 0.2
phases:
  pre_build: 
    commands: 
    - echo Logging in to Docker Registry.... 
    - echo $DOCKER_PASSWORD | docker login --username $DOCKER_USER --password-stdin
  build: 
    commands: 
    - echo Build started on `date` 
    - echo Building the Docker image... 
    - docker build -t $REPOSITORY_URI:latest .
  post_build: 
    commands: 
    - echo Build completed on `date` 
    - echo pushing to repo
    - docker push $REPOSITORY_URI:latest
    - echo Writing image definitions file... 
    - printf '[{"name":"%s","imageUri":"%s"}]' $CONTAINER_NAME $REPOSITORY_URI:latest > imagedefinitions.json
artifacts:
  files:
    - imagedefinitions.json
